{% set name = "libgsasl" %}
{% set version = "1.10.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://ftp.gnu.org/gnu/gsasl/{{ name }}-{{ version }}.tar.gz
  sha256: f1b553384dedbd87478449775546a358d6f5140c15cccc8fb574136fdc77329f

build:
  number: 0
  # This package is a dependency of libhdfs3, which is primarily used with HDFS on Linux.
  skip: True  # [win]
  run_exports:
    # unknown.  Leaving defaults.
    - {{ pin_subpackage('libgsasl') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
    - libtool  # [not win]
  host:
    - libgcrypt
    - libntlm
    - krb5

test:
  commands:
    - test -f $PREFIX/include/gsasl-compat.h
    - test -f $PREFIX/include/gsasl-mech.h
    - test -f $PREFIX/include/gsasl.h
    - test -f $PREFIX/lib/libgsasl.a
    - test -f $PREFIX/lib/libgsasl.so         # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7       # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7.9.6   # [linux]

about:
  home: http://www.gnu.org/software/gsasl/
  license: LGPL-2.1
  license_family: LGPL
  summary: Implementation of the Simple Authentication and Security Layer framework

extra:
  recipe-maintainers:
    - koverholt
    - martindurant
    - mariusvniekerk
