{% set name = "libgsasl" %}
{% set version = "1.10.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://ftp.gnu.org/gnu/gsasl/{{ name }}-{{ version }}.tar.gz
  sha256: f1b553384dedbd87478449775546a358d6f5140c15cccc8fb574136fdc77329f

build:
  number: 0
  # This package is a dependency of libhdfs3, which is primarily used with HDFS on Linux.
  # It's currently not available on s390x and there is no libgcrypt on s390x.
  skip: True  # [win or s390x]
  run_exports:
    # unknown.  Leaving defaults.
    - {{ pin_subpackage('libgsasl') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
    - libtool  # [not win]
  host:
    - krb5
    - libgcrypt
    - libgpg-error
    - libntlm
    - openssl
  run:
    - krb5
    - libgcrypt
    - libgpg-error
    - libntlm >=0.3.1
    - openssl

test:
  commands:
    - test -f $PREFIX/include/gsasl-compat.h
    - test -f $PREFIX/include/gsasl-mech.h
    - test -f $PREFIX/include/gsasl.h
    - test -f $PREFIX/lib/libgsasl.a
    - test -f $PREFIX/lib/libgsasl.so         # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7       # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7.10.0   # [linux]
    - test -f $PREFIX/lib/libgsasl$SHLIB_EXT  # [unix]
    - test -f $PREFIX/lib/libgsasl.7.dylib    # [osx]

about:
  home: http://www.gnu.org/software/gsasl/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: 
    - COPYING.LIB
    - COPYING
  summary: Implementation of the Simple Authentication and Security Layer framework
  doc_url: https://www.gnu.org/software/gsasl/manual/
  dev_url: https://git.savannah.gnu.org/cgit/gsasl.git

extra:
  recipe-maintainers:
    - koverholt
    - martindurant
    - mariusvniekerk
