{% set name = "libgsasl" %}
{% set version = "1.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/gsasl/{{ name }}-{{ version }}.tar.gz
  sha256: f1b553384dedbd87478449775546a358d6f5140c15cccc8fb574136fdc77329f

build:
  number: 2
  # This package is a dependency of libhdfs3, which is primarily used with HDFS on Linux.
  skip: true  # [win]
  run_exports:
    # unknown.  Leaving defaults.
    - {{ pin_subpackage('libgsasl') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - libtool  # [not win]
    - make     # [unix]
  host:
    - libkrb5 {{ krb5 }}
    - libgcrypt {{ libgcrypt }}
    - libgpg-error {{ libgpg_error }}  # [linux]
    - libntlm {{ libntlm }}

test:
  commands:
    - test -f $PREFIX/include/gsasl-compat.h
    - test -f $PREFIX/include/gsasl-mech.h
    - test -f $PREFIX/include/gsasl.h
    - test -f $PREFIX/lib/libgsasl.7.dylib    # [osx]
    - test -f $PREFIX/lib/libgsasl.a
    - test -f $PREFIX/lib/libgsasl.so         # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7       # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7.10.0  # [linux]
    - test -f $PREFIX/lib/libgsasl$SHLIB_EXT  # [unix]

about:
  home: https://www.gnu.org/software/gsasl/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file:
    - COPYING.LIB
    - COPYING
  summary: Implementation of the Simple Authentication and Security Layer framework
  doc_url: https://www.gnu.org/software/gsasl/manual/
  dev_url: https://git.savannah.gnu.org/cgit/gsasl.git

extra:
  recipe-maintainers:
    - koverholt
    - martindurant
    - mariusvniekerk
