{% set name = "libgsasl" %}
{% set version = "1.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/gsasl/{{ name }}-{{ version }}.tar.gz
  sha256: f1b553384dedbd87478449775546a358d6f5140c15cccc8fb574136fdc77329f

build:
  number: 3
  skip: true  # [win]
  run_exports:
    # Unknown. Leaving defaults.
    - {{ pin_subpackage(name) }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - libtool  # [not win]
    - make     # [unix]
    - pkg-config
  host:
    - libkrb5 {{ krb5 }}
    - libgcrypt {{ libgcrypt }}
    - libgpg-error {{ libgpg_error }}  # [linux]

test:
  commands:
    # Header files
    - test -f $PREFIX/include/gsasl-compat.h
    - test -f $PREFIX/include/gsasl-mech.h
    - test -f $PREFIX/include/gsasl.h
    # Library files
    - test -f $PREFIX/lib/libgsasl.a
    - test -f $PREFIX/lib/libgsasl.7.dylib    # [osx]
    - test -f $PREFIX/lib/libgsasl.dylib      # [osx]
    - test -f $PREFIX/lib/libgsasl.so         # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7       # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7.10.0  # [linux]
    - test -f $PREFIX/lib/libgsasl$SHLIB_EXT  # [unix]
    # pkgconfig file
    - test -f $PREFIX/lib/pkgconfig/libgsasl.pc
    # Locale files (Linux only)
    - for locale in $PREFIX/share/locale/*/LC_MESSAGES/libgsasl.mo; do test -f $locale; done  # [linux]

about:
  home: https://www.gnu.org/software/gsasl
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file:
    - COPYING.LIB
    - COPYING
  summary: Implementation of the Simple Authentication and Security Layer framework
  description: |
    GNU SASL is an implementation of the Simple Authentication and Security Layer framework
    and a few common SASL mechanisms. SASL is used by network servers (e.g., IMAP, SMTP, XMPP)
    to request authentication from clients, and in clients to authenticate against servers.
  doc_url: https://www.gnu.org/software/gsasl/manual
  dev_url: https://cgit.git.savannah.gnu.org/cgit

extra:
  recipe-maintainers:
    - koverholt
    - martindurant
    - mariusvniekerk
