{% set name = "libgsasl" %}
{% set version = "1.10.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/gsasl/{{ name }}-{{ version }}.tar.gz
  sha256: f1b553384dedbd87478449775546a358d6f5140c15cccc8fb574136fdc77329f

build:
  number: 2
  # This package is a dependency of libhdfs3, which is primarily used with HDFS on Linux.
  skip: true  # [win]
  run_exports:
    # unknown.  Leaving defaults.
    - {{ pin_subpackage('libgsasl') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - libtool  # [not win]
    - make     # [unix]
  host:
    - libkrb5 {{ krb5 }}
    - libgcrypt {{ libgcrypt }}
    - libgpg-error {{ libgpg_error }}  # [linux]
    - libntlm {{ libntlm }}

test:
  commands:
    # Header files
    - test -f $PREFIX/include/gsasl-compat.h
    - test -f $PREFIX/include/gsasl-mech.h
    - test -f $PREFIX/include/gsasl.h
    # Library files
    - test -f $PREFIX/lib/libgsasl.a
    - test -f $PREFIX/lib/libgsasl.7.dylib    # [osx]
    - test -f $PREFIX/lib/libgsasl.dylib      # [osx]
    - test -f $PREFIX/lib/libgsasl.so         # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7       # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7.10.0  # [linux]
    - test -f $PREFIX/lib/libgsasl$SHLIB_EXT  # [unix]
    # pkgconfig file
    - test -f $PREFIX/lib/pkgconfig/libgsasl.pc
    # Locale files (Linux only)
    - test -f $PREFIX/share/locale/da/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/de/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/en@boldquot/LC_MESSAGES/libgsasl.mo  # [linux]
    - test -f $PREFIX/share/locale/en@quot/LC_MESSAGES/libgsasl.mo      # [linux]
    - test -f $PREFIX/share/locale/eo/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/es/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/fi/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/fr/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/ga/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/hu/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/id/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/it/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/nl/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/pl/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/pt_BR/LC_MESSAGES/libgsasl.mo  # [linux]
    - test -f $PREFIX/share/locale/ro/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/sk/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/sr/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/sv/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/uk/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/vi/LC_MESSAGES/libgsasl.mo    # [linux]
    - test -f $PREFIX/share/locale/zh_CN/LC_MESSAGES/libgsasl.mo  # [linux]

about:
  home: https://www.gnu.org/software/gsasl/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file:
    - COPYING.LIB
    - COPYING
  summary: Implementation of the Simple Authentication and Security Layer framework
  doc_url: https://www.gnu.org/software/gsasl/manual/
  dev_url: https://git.savannah.gnu.org/cgit/gsasl.git

extra:
  recipe-maintainers:
    - koverholt
    - martindurant
    - mariusvniekerk
