{% set version = "1.8.1" %}

package:
  name: libgsasl
  version: "{{ version }}"

source:
  fn: libgsasl-{{ version }}.tar.gz
  url: ftp://ftp.gnu.org/gnu/gsasl/libgsasl-{{ version }}.tar.gz
  sha256: 19e2f90525c531010918c50bb1febef0d7115d620150cc66153b9ce73ff814e6

build:
  number: 0
  # This package is a dependency of libhdfs3, which is primarily used with HDFS on Linux.
  skip: True  # [win]
  run_exports:
    # unknown.  Leaving defaults.
    - {{ pin_subpackage('libgsasl') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
  host:
    - libgcrypt
    - libntlm
    - krb5

test:
  commands:
    - test -f $PREFIX/include/gsasl-compat.h
    - test -f $PREFIX/include/gsasl-mech.h
    - test -f $PREFIX/include/gsasl.h
    - test -f $PREFIX/lib/libgsasl.a
    - test -f $PREFIX/lib/libgsasl.so         # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7       # [linux]
    - test -f $PREFIX/lib/libgsasl.so.7.9.6   # [linux]

about:
  home: http://www.gnu.org/software/gsasl/
  license: LGPL-2.1
  license_family: LGPL
  summary: Implementation of the Simple Authentication and Security Layer framework

extra:
  recipe-maintainers:
    - koverholt
    - martindurant
    - mariusvniekerk
