# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dRit0qo634jS8AFehHreOtLHfI4qmY3/71jrOVIj1iB4FyWnSAV7R/rZ7rFKbJB1UK9WTzTBqGWYqo6rZVc5g5ZNum0T9158FpV9Cos5bfmukdgWuuyRAVnHAwv1pnfPY/P+iXlGmHjZ29WkUsomfVNfflGZSsZcThtO558YWYMd2hZCCtABS4dVeyV6/8ICoLVZaALB+UY98VCQW/ZSvgwpg7ERdilnkcxYSCHjayrTpGETVRGniRF0PpHq0TQNpM15HjpAhACATxEmFebHAa0dkjvXGnP8mY+L314dcqR4Jx1TNDMeEATHWDou9oBc1yHPHHxUambjJ2+kRVrVKYIYZ3r+GoxaPsbote6mdqWw92G+QKczfmIm5N/G45mL1aKR8x2kLsNxgCEpTaYZLTdu/IKJROrEa6XXv1uQVWM9TWIdcovOwKZwuml0dg3xQ+dSTBWQP4aolCA61RdVNI/ydTcZud1L1EEgefqwq9Ucn2Y2rp+O7q43bYS6pks7pnxrmX+CYUuYqpuJzROli7RKYgDnYDe95v6hX+iwun8gwKf+R0/lM3q4S2naO8Kkzuk+fnO+fzQJghWtAp1LYiTbWX/3JMfiGAjZ1WPPI1cAjnPMNjU69lta9/vCghRhU1enMFvxeNw7ABuSfU1N8O8rxpsTCCEVW7FLWi4FTsY="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
