travis:
  secure:
    BINSTAR_TOKEN: dRit0qo634jS8AFehHreOtLHfI4qmY3/71jrOVIj1iB4FyWnSAV7R/rZ7rFKbJB1UK9WTzTBqGWYqo6rZVc5g5ZNum0T9158FpV9Cos5bfmukdgWuuyRAVnHAwv1pnfPY/P+iXlGmHjZ29WkUsomfVNfflGZSsZcThtO558YWYMd2hZCCtABS4dVeyV6/8ICoLVZaALB+UY98VCQW/ZSvgwpg7ERdilnkcxYSCHjayrTpGETVRGniRF0PpHq0TQNpM15HjpAhACATxEmFebHAa0dkjvXGnP8mY+L314dcqR4Jx1TNDMeEATHWDou9oBc1yHPHHxUambjJ2+kRVrVKYIYZ3r+GoxaPsbote6mdqWw92G+QKczfmIm5N/G45mL1aKR8x2kLsNxgCEpTaYZLTdu/IKJROrEa6XXv1uQVWM9TWIdcovOwKZwuml0dg3xQ+dSTBWQP4aolCA61RdVNI/ydTcZud1L1EEgefqwq9Ucn2Y2rp+O7q43bYS6pks7pnxrmX+CYUuYqpuJzROli7RKYgDnYDe95v6hX+iwun8gwKf+R0/lM3q4S2naO8Kkzuk+fnO+fzQJghWtAp1LYiTbWX/3JMfiGAjZ1WPPI1cAjnPMNjU69lta9/vCghRhU1enMFvxeNw7ABuSfU1N8O8rxpsTCCEVW7FLWi4FTsY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
